env_vars:
  base_key_path: /service/workspace-test/
  secrets:
  - DB_HOST
  - DB_PASSWORD
  - APM_API_KEY
  - API_VERSION
  - BASE_URL
  - TOKEN_SUFFIX_CODE
  - DB_PW
  - DB_USERNAME
  - DB_READER_PORT
  - DB_READER_HOST
  - DB_READER_LOG_PATH
