AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure for workspace service handling.."

Metadata:
  Name: "MS-Workspace"
  StagingStackName: "staging--ms-workspace"
  ProductionStackName: "production--ms-workspace"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - "staging"
      - "production"
  BucketName:
    Type: String
    Default: "main-bucket-access-logs"
  LogPath:
    Type: String
    Default: "access-logs"
  BackupBucketName:
    Type: String

Resources:
  WorkspaceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}--workspace-service-role"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref WorkspaceServiceManagedPolicy

  WorkspaceServiceManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Rescan Initializer Policy"
      ManagedPolicyName: !Sub "${Environment}--workspace-service-policy"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}"
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}/${LogPath}/*"

Outputs:
  BackupBucket:
    Description: "Backup S3 Bucket"
    Value: !Ref BackupBucketName
