AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure for log handling...."

Metadata:
  Entity: infra/media-service
  StackPostfix: medisa-service
  StackRegion: ap-southeast-1
  UUID: 8b9b8035-004f-4d8d-bf8d-7b8d1878a40d

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - "staging"
      - "production"
  BucketName:
    Type: String
    Default: "main-bucket-access-logs"
  LogPath:
    Type: String
    Default: "access-logs"

Resources:
  MediaServiceFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}--medis-service-role"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref MediaServiceManagedPolicy

  MediaServiceManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Rescan Initializer Policy"
      ManagedPolicyName: !Sub "${Environment}--media-service-policy"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}"
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}/${LogPath}/*"
