AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure for log handling....."

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - "staging"
      - "production"
  BucketName:
    Type: String
    Default: "main-bucket-access-logs"
  LogPath:
    Type: String
    Default: "access-logs"

Resources:
  ScannerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}--scanner-service-role"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref ScannerServiceManagedPolicy

  ScannerServiceManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Rescan Initializer Policy"
      ManagedPolicyName: !Sub "${Environment}--scanner-service-policy"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}"
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}/${LogPath}/*"
