steps:
  - command: ls
    env:
        BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
    plugins:
      - hasithaishere/buildkite-file-counter#v1.0.0:
          pattern: '*.md'
  - command: "bie init -e staging -r ap-southeast-1 -b $BUILDKITE_BUILD_NUMBER -o $BUILDKITE_ORGANIZATION_SLUG -p $BUILDKITE_PIPELINE_NAME | buildkite-agent pipeline upload"
    label: "Initialize Pipeline"
