steps:
  - label: "Initialize IaC Deployment"
    command: "service/lambda/notify/.buildkite/scripts/post-checkout"
    key: "ms-notify-iac"
    plugins:
      - respond-io/iac-executor#v0.2.11:
          type: 'lambda'
          name: 'MS-Notify'
          path: 'service/lambda/notify/template.yaml'
