steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "ms-notify-iac"
    plugins:
      - respond-io/iac-executor#v0.2.10:
          type: 'lambda'
          name: 'MS-Notify'
          path: 'service/lambda/notify/template.yaml'
