steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "ms-notify-iac"
    plugins:
      - respond-io/iac-executor#v0.1.2:
          type: 'lambda'
          name: 'MS-Notify'
          stack: 'ms-notify'
          path: 'service/lambda/notify/template.yaml'
  - label: "Deploy"
    command: "service/lambda/notify/.buildkite/scripts/deploy"
    depends_on: "ms-notify-iac"
