steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "ms-notify-iac"
    plugins:
      - respond-io/iac-executor#v0.2.16:
          type: 'lambda'
          name: 'MS-Notify'
          path: 'service/lambda/notify/template.yaml'
          command: 'pwd && cd service/lambda/notify && ./npm-install.sh && cd "${BUILDKITE_BUILD_CHECKOUT_PATH}" && pwd'
