steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    plugins:
      - respond-io/iac-executor#v0.3.4:
          type: 'lambda'
          name: 'MS-Notify'
          path: 'service/lambda/notify/template.yaml'
          command: 'cd service/lambda/notify && ./npm-install.sh'