steps:
  - group: ":aws-lambda: MS Notify Lambda"
    key: "ms-notify-lambda-group"
    steps:
      - label: "Initialize IaC Deployment"
        command: "ls"
        plugins:
          - respond-io/iac-executor#v0.3.0:
              type: 'lambda'
              name: 'MS-Notify'
              path: 'service/lambda/notify/template.yaml'
              command: 'cd service/lambda/notify && ./npm-install.sh'