steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "iac"
    plugins:
      - respond-io/iac-executor-buildkite-plugin#v0.1.0:
          type: 'lambda'
          name: 'MS-Notify'
          stack: 'ms-notify'
          path: 'service/lambda/notify/template.yaml'
  - label: "Deploy"
    command: "service/lambda/notify/.buildkite/scripts/deploy"
    depends_on: "iac"
