steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    env:
        BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"
    plugins:
      - hasithaishere/buildkite-file-counter#v1.1.9:
          type: 'lambda'
          name: 'MS Notify'
          stack: 'ms-notify'
          path: 'service/lambda/notify'
  - label: "Deploy"
    command: "service/lambda/notify/.buildkite/scripts/deploy"
