AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure for base AWS config.."

Metadata:
  Name: "Infra-IAM-User-Stg"
  StagingStackName: "staging--iam-resources-user-18"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - "staging"
      - "production"
  BucketName:
    Type: String
    Default: "main-bucket-access-logs"
  LogPath:
    Type: String
    Default: "access-logs"

Resources:
  BaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}--iam-resources-user-stg"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref BaseManagedPolicy

  BaseManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Base Policy"
      ManagedPolicyName: !Sub "${Environment}--Base-policy-user-stg"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:GetObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}"
              - !Sub "arn:aws:s3:::${Environment}--${BucketName}/${LogPath}/*"
