AWSTemplateFormatVersion: "2010-09-09"
Description: "Infrastructure for base AWS config.."

Metadata:
  Name: "IAM-User-22"
  StagingStackName: "staging--iam-resources-user-22"

Resources:
  BaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "staging--iam-resources-user-stg-22"
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref BaseManagedPolicy

  BaseManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Base Policy"
      ManagedPolicyName: !Sub "staging--Base-policy-user-stg-22"
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:GetObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::${Environment}--master-bucket"
              - !Sub "arn:aws:s3:::${Environment}--master-bucket/log-path-1/*"
