steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "iac"
    plugins:
      - respond-io/iac-executor-buildkite-plugin#v0.1.0:
          type: 'ecs'
          name: 'MS-Scanner'
          stack: 'ms-scanner'
          path: 'service/scanner/template.yaml'
  - label: "Build"
    command: "service/scanner/.buildkite/scripts/docker-build"
    key: "scanner-build"
    depends_on: "iac"
  - label: "Deploy"
    command: "service/scanner/.buildkite/scripts/deploy"
    depends_on: "scanner-build"
