steps:
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "ms-scanner-iac"
    plugins:
      - respond-io/iac-executor#v0.1.1:
          type: 'ecs'
          name: 'MS-Scanner'
          stack: 'ms-scanner'
          path: 'service/scanner/template.yaml'
  - label: "Build"
    command: "service/scanner/.buildkite/scripts/docker-build"
    key: "scanner-build"
    depends_on: "ms-scanner-iac"
  - label: "Deploy"
    command: "service/scanner/.buildkite/scripts/deploy"
    depends_on: "scanner-build"
