steps:
  - block: ":hammer_and_wrench: Continue Scanner ECS Deployment?"
    if: build.branch == "master"
  - label: "Initialize IaC Deployment"
    command: "ls"
    key: "ms-scanner-iac"
    plugins:
      - respond-io/iac-executor#v0.3.33:
          type: 'ecs'
          name: 'MS-Scanner'
          path: 'service/scanner/template.yaml'
  - label: "Build"
    command: "service/scanner/.buildkite/scripts/docker-build"
    key: "scanner-build"
    depends_on: "ms-scanner-iac"
  - label: "Deploy"
    command: "service/scanner/.buildkite/scripts/deploy"
    key: "scanner-deploy"
    depends_on: "scanner-build"
  - label: "Tag MS-Scanner ECS Build"
    command: "bsm set -o $BUILDKITE_ORGANIZATION_SLUG -p $BUILDKITE_PIPELINE_SLUG -h $BUILDKITE_COMMIT -s service/scanner"
    depends_on: "scanner-deploy"