steps:
  - block: ":rocket: Continue Web-Chat deployment?"
    if: build.branch == "master"
  - label: "Webchat Build & Upload Artifacts"
    command: "web/webchat/.buildkite/scripts/docker-build-and-upload"
    key: "build-webchat"
  - label: "Invalidate Cache"
    command: "web/webchat/.buildkite/scripts/invalidate-cache"
    depends_on: "build-webchat"
