#!/bin/bash

set -ueo pipefail

LATEST_BUILT_TAG=$(head -n 1 ~/last_successful_production_build)

echo $BUILDKITE_BUILD_CHECKOUT_PATH
echo $BUILDKITE_ORGANIZATION_SLUG
echo $BUILDKITE_PIPELINE_SLUG
echo $BUILDKITE_COMMIT
echo "${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite/main.yml"

bsm --help

#git diff --name-only $LATEST_BUILT_TAG
bsm diff -r $BUILDKITE_BUILD_CHECKOUT_PATH -c "${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite/main.yml" -o $BUILDKITE_ORGANIZATION_SLUG -p $BUILDKITE_PIPELINE_SLUG -h $BUILDKITE_COMMIT