#!/bin/bash

# Deploying the Lambda using SAM
#  The samconfig.toml should be configured with confirm_changset = false

echo "--- Deploying using SAM ..."

cd service/lambda/notify

./npm-install.sh

sam deploy --no-fail-on-empty-changeset
