name: Stage 2 - Tagging and Releasing

on:
  pull_request:
    types: [ closed ]
    branches:
      - master

jobs:
  release:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Package Version
        id: package_version
        run: echo "::set-output name=version::$(jq -r '.version' package.json)"

      - name: Get PR Description
        id: pr_description
        run: echo "::set-output name=description::$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body')"

      - name: Create Tag
        id: create_tag
        run: |
          version="${{ steps.package_version.outputs.version }}"
          tag_name="v${version}"
          gh release create "$tag_name" --notes ""

      - name: Create Release
        run: |
          version="${{ steps.package_version.outputs.version }}"
          description="${{ steps.pr_description.outputs.description }}"
          gh release edit "v${version}" --notes "$description"