name: Stage 1 - Create Release PR

on:
  pull_request:
    types: [ closed ]
    branches:
      - master

jobs:
  release:
    if: github.event.pull_request.merged && (startsWith(github.event.pull_request.head.ref, 'flight/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))
    runs-on: ubuntu-latest
    name: Tag and Release
    steps:
      - name: Release
        uses: respond-io/release-management-action@flight/implement-pr-process
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/config/release-management.yaml
          release-prefix: v
